version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: jelislabible_postgres
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: jelislabible
      POSTGRES_PASSWORD: bible
      POSTGRES_DB: jelislabible
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
